### PR TITLE
Added showing of author(s) in post and supported multiple author field

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

### CODE REVIEW

**Review by sahilsuneja1 — APPROVED** [review]

**Comment by InTheCloudDan** [comment]
This is currently breaking with multiple authors:
`  <meta content="http://0.0.0.0:4000/authors/lumjjbricarkol" property="article:author">`

I'll try to take a deeper look at it during my lunch time or tonight to see how to get it sorted and if this schema supports multiple authors. Otherwise may just have to choose first one.

**Review by InTheCloudDan — APPROVED** [review]
last commit fixed my concerns.

**Comment by sahilsuneja1** [comment]
I actually liked not showing authors in the blog. Had more of a team vibe to it. For example, the kata fs bug vuln blog post, had inputs from all of us!

**Comment by lumjjb** [comment]
I think it is nice to show different people writing, it also shows the team vibe in a different sense, that everyone is contributing and are exploring different things in the group. In this way, hopefully we can encourage others in the community to write blog posts too, not just us!

For credit for others' contribution, now that we have multiple authors, we can do that too :).

**Comment by sahilsuneja1** [comment]
okie dokie :)

**Pull request merged**
